# Generated by Django 3.2 on 2021-05-14 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='proco',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='criando',
        ),
        migrations.AddField(
            model_name='produto',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de Atuação'),
        ),
    ]
